### ISSUE TITLE
Problem cast with complex

### ISSUE THREAD

**Issue by zimoun** [andrenarchy/krypy#52]
If `A` is defined by `scipy.sparse.linalg.LinearOperator` with `dtype=complex`,
then, it appears that a cast is not supported  in `utils.py: l.1081`.
~~~
TypeError: Cannot cast ufunc subtract output from dtype('complex128')
to dtype('float64') with casting rule 'same_kind'
~~~
IPython says this line:   `Av -= alpha * self.V[:, [j]]`

Snippet of code to reproduce it (or not?)
~~~python
import numpy
import scipy.sparse.linalg
from krypy.linsys import LinearSystem, Gmres

N = 50
A = scipy.sparse.linalg.LinearOperator((N, N), matvec=f, dtype=complex)
b = numpy.random.rand(A.shape[0]) + 1j * numpy.random.rand(A.shape[0])

m = 3

linear_system = LinearSystem(A, b)
solver = Gmres(linear_system, maxiter=m)
~~~

**Comment by andrenarchy** [comment]
Can you provide the matvec function `f`? Currently it's undefined...
```
NameError: name 'f' is not defined
```

**Comment by zimoun** [comment]
it was for any function `f` defined with `dtype=float`.
If you cannot reproduce the behavior, then it is not a bug of your nice package but from my installation.
So, sorry.

**Comment by andrenarchy** [comment]
No problem, I'm glad you could solve it! :smile: Feel free to open issues if you think that something is wrong...
