### ISSUE TITLE
Pip dependency possibly missing

### ISSUE THREAD

**Issue by homocomputeris** [andrenarchy/krypy#59]
Hi,
I want to build an ArchLinux package for KryPy but the tool fails because `pip` doesn't detect NumPy when being installed:

https://github.com/sollidsnake/pipman/issues/11#issuecomment-304732164

Could you check this, please?

**Comment by andrenarchy** [comment]
Thanks for reporting! I think that's an issue in `setup.py`: `requires` should probably be `install_requires`. I'll take a look later.

**Comment by andrenarchy** [comment]
@homocomputeris can you try again in your setting? It works for me now.

**Comment by homocomputeris** [comment]
It works. Thanks!
