### ISSUE TITLE
Dead code in krypy.utils.norm()

### ISSUE THREAD

**Issue by stanleybak** [andrenarchy/krypy#61]
the function `krypy.utils.norm()` starts with the code:

```
if y is None:
        y = x
# Euclidean inner product?
if y is None and (ip_B is None
                  or isinstance(ip_B, IdentityLinearOperator)):
    return numpy.linalg.norm(x, 2)
```

It seems the second condition is never true, since if `y` is None it gets set to `x` after the first condition (`x` is never None otherwise norm doesn't make sense). This means that the Euclidean inner product is never used, and in this case the function returns the `sqrt` of the norm of the inner product of the vector with itself. This has different rounding behavior on my computer than calling `np.linalg.norm(x, 2)` (which strangely enough also rounds differently than `np.linalg.norm(x)` but that's numpy's fault).

Dead code can often indicate subtle bugs or performance issues; I just wanted to make sure that this was the intention.

**Comment by andrenarchy** [comment]
Thanks for reporting, you're absolutely right – good catch! I think the block 

```python
if y is None:
    y = x
```

should come after the other block. I will take another look at the code but it seems like it probably "only" degraded performance (and very likely the accuracy wasn't as good as numpy's `norm`).
