### ISSUE TITLE
LinearOperator.dot unreachable condition?

### ISSUE THREAD

**Issue by homocomputeris** [andrenarchy/krypy#63]
Hi,
I've encountered this snippet:
https://github.com/andrenarchy/krypy/blob/4883ec9a61d64ea56489e15c35cc40f0633ab2f1/krypy/utils.py#L1360

The conditions seems unreachable. Or array's dimension can be 0 in some cases?

**Comment by andrenarchy** [comment]
Yeah, arrays can have zero dimensions (for example `numpy.zeros((5, 0))`) and it can be quite handy so you don't need to treat edge cases differently. Like, imagine you have a selection algorithm for vectors that are used in deflation for speeding up the computation. And sometimes this algorithm might decide to just pick no vectors at all. Then an orthonormal basis of this would be an N-by-0 array. I hope that makes sense? :)

I'm closing this for now. Just let me know here if you think we should discuss more about this!
