### ISSUE TITLE
sqrt(norm(x))

### ISSUE THREAD

**Issue by nschloe** [andrenarchy/krypy#80]
Taking the sqrt _and_ the norm looks like a bug.
https://github.com/andrenarchy/krypy/blob/master/krypy/utils.py#L238

**Comment by andrenarchy** [comment]
To me it looks fine. It's `\sqrt{||<x,y>||}` where the norm could actually be replaced by abs(). I guess I took that shortcut so I don't have to deal with array shapes and always get a scalar?
